# Generated by Django 4.0.3 on 2022-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('cardNum', models.CharField(blank=True, max_length=16, null=True, verbose_name='card number')),
                ('epxpirationDate', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('securityCode', models.CharField(blank=True, max_length=3, null=True, verbose_name='security Code')),
            ],
        ),
    ]
