# Generated by Django 4.0.4 on 2022-05-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors_profile',
            options={'verbose_name': 'Doctor_profile', 'verbose_name_plural': 'Doctors_profiles'},
        ),
        migrations.AddField(
            model_name='doctors_profile',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='Doctors_profile', verbose_name='Personal Image'),
        ),
        migrations.AlterField(
            model_name='doctors_profile',
            name='phone_num',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
    ]
