# Generated by Django 4.0.3 on 2022-05-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_doctors_profile_phone_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors_profile',
            name='phone_number',
            field=models.CharField(default='', max_length=11, verbose_name='Phone'),
        ),
    ]
