# Generated by Django 4.0.3 on 2022-05-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_doctors_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='appointments')),
            ],
        ),
        migrations.AddField(
            model_name='doctors_profile',
            name='DocTime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.doc_time', verbose_name='Doctor '),
        ),
    ]
